# Generated by Django 4.0.5 on 2022-06-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('question', 'user'), name='unique_favorite'),
        ),
    ]
