# Generated by Django 4.0.5 on 2022-06-08 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_question_favorited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_accepter',
        ),
    ]
