# Generated by Django 4.0.5 on 2022-06-06 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_favorite_unique_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='description',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='title',
        ),
        migrations.DeleteModel(
            name='Accepted',
        ),
    ]
