# Generated by Django 4.0.5 on 2022-06-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_answer_accepted_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='response',
            field=models.TextField(max_length=300),
        ),
    ]
