# Generated by Django 4.0.5 on 2022-06-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_question_created_at'),
        ('api', '0003_alter_answer_response'),
    ]

    operations = [
    ]
