# Generated by Django 4.0.5 on 2022-06-09 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_mylist_question_alter_mylist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylist',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_lists', to='api.question'),
        ),
        migrations.AlterField(
            model_name='mylist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
