# Generated by Django 4.0.5 on 2022-06-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_answer_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='favorite',
        ),
        migrations.AddField(
            model_name='question',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
