# Generated by Django 4.0.5 on 2022-06-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_question_favorited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
