# Generated by Django 4.0.5 on 2022-06-07 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_answer_modified_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='favorited_by',
            field=models.ManyToManyField(related_name='question', to=settings.AUTH_USER_MODEL),
        ),
    ]
