# Generated by Django 4.0.5 on 2022-06-07 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_question_favorited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
