# Generated by Django 4.0.5 on 2022-06-03 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_question_created_at 2'),
        ('api', '0005_remove_user_created_at'),
    ]

    operations = [
    ]
